from wtforms import Form, StringField, SubmitField, validators, DecimalField, TextAreaField

class AdminLoginForm(Form):
    #username = StringField('username')
    #password = StringField('password')
    username = StringField('Username')
    password = StringField('Password')
    submit = SubmitField('Submit')

class AddSmileForm(Form):
    #smiles = TextAreaField('smiles')
    smiles = TextAreaField('SMILE')
    # inchiKey = StringField('inchiKey')
    # homo = DecimalField('homo')
    # lumo = DecimalField('lumo')
    # verticalExcitationEnergy = DecimalField('verticalExcitationEnergy')
    # redoxPotentialS0 = DecimalField('redoxPotentialS0')
    # redoxPotentialS1 = DecimalField('redoxPotentialS1')
    # redoxPotentialT1 = DecimalField('redoxPotentialT1')
    # dipoleMomentS0 = DecimalField('dipoleMomentS0')
    # dipoleMomentS1 = DecimalField('dipoleMomentS1')
    # dipoleMomentT1 = DecimalField('dipoleMomentT1')
    # ionizationPotential = DecimalField('ionizationPotential')
    # s1 = DecimalField('s1')
    # t1 = DecimalField('t1')
    submit = SubmitField('Submit')


class AddSmileToDBForm(Form):
    smiles = StringField('smiles')
    inchiKey = StringField('inchiKey')
    homo = DecimalField('homo')
    lumo = DecimalField('lumo')
    verticalExcitationEnergy = DecimalField('verticalExcitationEnergy')
    redoxPotentialS0 = DecimalField('redoxPotentialS0')
    redoxPotentialS1 = DecimalField('redoxPotentialS1')
    redoxPotentialT1 = DecimalField('redoxPotentialT1')
    dipoleMomentS0 = DecimalField('dipoleMomentS0')
    dipoleMomentS1 = DecimalField('dipoleMomentS1')
    dipoleMomentT1 = DecimalField('dipoleMomentT1')
    ionizationPotential = DecimalField('ionizationPotential')
    zero0s1 = DecimalField('zero0s1')
    zero0t1 = DecimalField('zero0t1')
    submit = SubmitField('Submit')


class SearchSmileForm(Form):
    #smiles = StringField('smiles')
    #inchiKey = StringField('inchiKey')
    #homo = StringField('homo')
    #lumo = StringField('lumo')
    #verticalExcitationEnergy = StringField('verticalExcitationEnergy')
    #redoxPotentialS0 = StringField('redoxPotentialS0')
    #redoxPotentialS1 = StringField('redoxPotentialS1')
    #redoxPotentialT1 = StringField('redoxPotentialT1')
    #dipoleMomentS0 = StringField('dipoleMomentS0')
    #dipoleMomentS1 = StringField('dipoleMomentS1')
    #dipoleMomentT1 = StringField('dipoleMomentT1')
    #ionizationPotential = StringField('ionizationPotential')
    #s1 = StringField('s1')
    #t1 = StringField('t1')
    #search = SubmitField('search')
    # Z. Hu, we don't really need SMILES or InChIKey for searching
    smiles = StringField('SMILE')
    inchiKey = StringField('InChIKey')
    homo = StringField('HOMO (eV)')
    lumo = StringField('LUMO (eV)')
    verticalExcitationEnergy = StringField('Vertical Excitation Energy (eV)')
    redoxPotentialS0 = StringField('Redox Potential S<sub>0</sub> (eV)')
    redoxPotentialS1 = StringField('Redox Potential S<sub>1</sub> (eV)')
    redoxPotentialT1 = StringField('Redox Potential T<sub>1</sub> (eV)')
    dipoleMomentS0 = StringField('Dipole Moment S<sub>0</sub> (D)')
    dipoleMomentS1 = StringField('Dipole Moment S<sub>1</sub> (D)')
    dipoleMomentT1 = StringField('Dipole Moment T<sub>1</sub> (D)')
    ionizationPotential = StringField('Ionization Potential (eV)')
    zero0s1 = StringField('0-0 S<sub>1</sub> (eV)')
    zero0t1 = StringField('0-0 T<sub>1</sub> (eV)')
    search = SubmitField('Search')
